version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-apache-php
    volumes:
      - ./src:/var/www/html
      - ./ssl:/etc/ssl
      - ./fonts:/usr/share/fonts
    ports:
      - "8080:80"
      - "8043:443"
    networks:
      - my_bridge_network
    container_name: webserver

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_bridge_network
    container_name: mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - my_bridge_network
    container_name: phpmyadmin

volumes:
  db_data:

networks:
  my_bridge_network:
